services:
  - type: web
    name: mr-robot-frontend
    env: static
    rootDir: website/fronted
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_ENV
        value: production
