services:
  - type: web
    name: mr-robot-frontend
    env: static
    buildCommand: cd website/fronted && npm install && npm run build
    staticPublishPath: website/fronted/build
    rewrites:
      - source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
